# Generated by Django 4.2.8 on 2026-04-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourtType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã loại sân')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên loại sân')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('INACTIVE', 'Ngưng hoạt động')], default='ACTIVE', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã sân')),
                ('name', models.CharField(max_length=100, verbose_name='Tên sân')),
                ('area', models.CharField(blank=True, max_length=50, null=True, verbose_name='Khu vực')),
                ('status', models.CharField(choices=[('READY', 'Sẵn sàng'), ('MAINTENANCE', 'Đang bảo trì'), ('INACTIVE', 'Ngưng hoạt động')], default='READY', max_length=20, verbose_name='Trạng thái sân')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('court_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courts', to='courts.courttype', verbose_name='Loại sân')),
            ],
        ),
    ]
