# Generated by Django 4.2.8 on 2026-04-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_table_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã bảng giá')),
                ('price_table_name', models.CharField(max_length=255, unique=True, verbose_name='Tên bảng giá')),
                ('apply_scope', models.CharField(choices=[('ALL', 'Tất cả sân'), ('SPECIFIC', 'Sân cụ thể')], default='ALL', max_length=10, verbose_name='Phạm vi áp dụng')),
                ('effective_date', models.DateField(verbose_name='Ngày hiệu lực')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('applied_days', models.JSONField(blank=True, default=list, verbose_name='Ngày áp dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('court_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tables', to='courts.courttype', verbose_name='Loại sân')),
            ],
            options={
                'verbose_name': 'Bang gia',
                'verbose_name_plural': 'Bang gia',
            },
        ),
        migrations.CreateModel(
            name='PriceTableTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Thứ tự')),
                ('price_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='pricing.pricetable', verbose_name='Bảng giá')),
            ],
            options={
                'verbose_name': 'Khung gio bang gia',
                'verbose_name_plural': 'Khung gio bang gia',
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='PriceTableCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_table_links', to='courts.court', verbose_name='Sân')),
                ('price_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_courts', to='pricing.pricetable', verbose_name='Bảng giá')),
            ],
            options={
                'verbose_name': 'Bang gia san ap dung',
                'verbose_name_plural': 'Bang gia san ap dung',
                'unique_together': {('price_table', 'court')},
            },
        ),
    ]
