# Generated by Django 4.2.8 on 2026-04-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã khách hàng')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Khach hang',
                'verbose_name_plural': 'Khach hang',
            },
        ),
    ]
