# Generated by Django 4.2.8 on 2026-04-27 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QLDonDat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã đơn đặt')),
                ('ten_khach_hang', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('so_dien_thoai', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('gio_bat_dau', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('gio_ket_thuc', models.TimeField(verbose_name='Giờ kết thúc')),
                ('loai_san', models.CharField(max_length=100, verbose_name='Loại sân')),
                ('san_ap_dung', models.CharField(max_length=100, verbose_name='Sân áp dụng')),
                ('ngay_dat', models.DateField(verbose_name='Ngày đặt')),
                ('tong_tien', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền')),
                ('trang_thai_don', models.CharField(choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Đã xác nhận', 'Đã xác nhận'), ('Hoàn thành', 'Hoàn thành'), ('Hủy', 'Hủy')], default='Chờ xác nhận', max_length=50, verbose_name='Trạng thái đơn')),
                ('thanh_toan', models.CharField(choices=[('Đã thanh toán', 'Đã thanh toán'), ('Chưa thanh toán', 'Chưa thanh toán')], default='Chưa thanh toán', max_length=50, verbose_name='Thanh toán')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Quản lý đơn đặt',
                'verbose_name_plural': 'Quản lý đơn đặt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên khách hàng')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('date', models.DateField(verbose_name='Ngày đặt')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('total_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy'), ('completed', 'Đã hoàn thành')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='courts.court', verbose_name='Sân')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.qldondat', verbose_name='Đơn hàng')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Dat san',
                'verbose_name_plural': 'Dat san',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('court', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
